# Generated by Django 4.1.5 on 2023-02-28 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_payments_year_month"),
    ]

    operations = [
        migrations.AddField(
            model_name="payments",
            name="month",
            field=models.IntegerField(blank=True, default=1, max_length=2),
        ),
        migrations.AddField(
            model_name="payments",
            name="type",
            field=models.CharField(default="out", max_length=3),
        ),
        migrations.AddField(
            model_name="payments",
            name="year",
            field=models.IntegerField(blank=True, default=1, max_length=4),
        ),
    ]
