# Generated by Django 4.1.5 on 2023-02-28 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_payments_month_payments_type_payments_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payments",
            name="month",
            field=models.IntegerField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name="payments",
            name="type",
            field=models.CharField(default="payments", max_length=3),
        ),
        migrations.AlterField(
            model_name="payments",
            name="year",
            field=models.IntegerField(blank=True, max_length=4),
        ),
    ]
