# Generated by Django 4.1.5 on 2023-02-28 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_alter_payments_month_alter_payments_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payments",
            name="type",
            field=models.CharField(default="payments", max_length=10),
        ),
    ]
