# Generated by Django 4.1.5 on 2023-02-28 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("income", "0002_income_year_month"),
    ]

    operations = [
        migrations.RemoveField(model_name="income", name="year_month",),
        migrations.AddField(
            model_name="income",
            name="month",
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name="income",
            name="year",
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
