# Generated by Django 4.1.5 on 2023-02-28 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("income", "0003_remove_income_year_month_income_month_income_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="income",
            name="type",
            field=models.CharField(default="in", max_length=3),
        ),
        migrations.AddField(
            model_name="income",
            name="year_month",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name="income",
            name="month",
            field=models.IntegerField(blank=True, default=1, max_length=2),
        ),
        migrations.AlterField(
            model_name="income",
            name="year",
            field=models.IntegerField(blank=True, default=1, max_length=4),
        ),
    ]
