# Generated by Django 4.1.5 on 2023-02-28 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("income", "0004_income_type_income_year_month_alter_income_month_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="income",
            name="month",
            field=models.IntegerField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name="income",
            name="type",
            field=models.CharField(default="income", max_length=3),
        ),
        migrations.AlterField(
            model_name="income",
            name="year",
            field=models.IntegerField(blank=True, max_length=4),
        ),
    ]
