# Generated by Django 4.1.5 on 2023-02-28 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("income", "0005_alter_income_month_alter_income_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="income",
            name="type",
            field=models.CharField(default="income", max_length=10),
        ),
    ]
